//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenAuthentication
    {
        public int Id { get; set; }
        public string StudentID { get; set; }
        public string Token { get; set; }
        public string Expire { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
